---
title: "O. Aishwarya's resume"
author: O. Aishwarya
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
---

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></I> O.Aishwarya@iiitb.ac.in
- <i class="fa fa-github"></i> [github.com/AishwaryaOthena](http://github.com/AishwaryaOthena/)
- <i class="fa fa-home"></i> [My Homepage](https://aishwaryaothena.github.io)

Summary {#Summary} 
--------------------------------------------------------------------------------

- I am a PhD candidate at the International Institute of Information Technology, Bangalore, working at the intersection of disability studies, accessibility and assistive technology to analyze educational systems for children who are blind and visually impaired living in the Global South.  

### Research Interests

- Disability studies and accessibility in the Global South
- Inclusive education
- Ethnography and action research

Skills {#skills}
--------------------------------------------------------------------------------

- #### Qualitative Research:

- Interested in understanding complex systems using qualitative research methodology such as ethnography and action research.

- #### Quantitative Research

- Has undertaken projects for data analysis using R and Python. 

- #### Accessibility Testing

-Document accessibility testing for Word, PdF, Excel, Pub and PowerPoint files.  

- #### Document Creation Environments

-Is familiar with creating documents using Markdown, RMarkdown, LaTex and Microsoft Office.

Main
================================================================================

O. Aishwarya {#title}
--------------------------------------------------------------------------------

Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Intern

Microsoft Research

Bangalore, India

January 2021 - July 2021

- Analysed and documented  the art-making practices of 10 visually impaired artists around the world.
    - Conducted studies to understand the semiotics of tactile art.

### Educational Coordinator

Vision Empower

Bangalore, India

2019 - 2020

- Responsibilities included the creation of accessible STEM content, development of teacher training modules, creation of accessible teaching learning materials, teacher training, designing student engagements for visually impaired  students in middle school using story-telling, games and technology.
    - Involved in the VICT project which aimed to inculcate computational thinking~(CT) concepts in children with visual impairments through play. This included creation and validation of resources, weekly school visits for play sessions, observation and reporting, and creating the CT curriculum with the team. 
    - Worked extensively on secondary research in order to generate key learning indicators of numeracy skills for students in Grades 1-4.
    - Involved in a research study on the attitudes and perceptions of teachers on introducing digital literacy through games. 
    - Evaluated  technologies such as TAG and HEXIS created at Vision Empower and IIITB for students with visual impairment.
    - Conducted a research pilot for online story telling as a pedagogical approach for children with visual impairment. 

### Research Intern

Grassroots Research and Advocacy Movement

Mysore, India

May 2018 - June 2018

-Worked on a research project titled **A Study to Understand Employment Needs and Opportunities for Persons with Disabilities in Mysore and Gadag Districts of Karnataka**
    - Conducted primary data collection through personal interviews of various stakeholders, undertook research writing and documentation.

### Research Intern

Centre for Development Studies

Trivandrum, India

May 2017

- Prepared and presented report titled **An Analysis of Mandatory Corporate Social Responsibility in India: Trends, Prospects and Challenges in the Post-Mandate Period**.

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### International Institute of Information Technology

PhD in It and Society (Currently Pursuing)

Bangalore, Karnataka, India

2020 - Present

- ** Area of work:** disability and assistive technology
- Interested in creating tactile art opportunities for children who are blind in India.

### Azim Premji University

MA. Development

Bangalore, Karnataka, India

2017 - 2019

- **CGPA**: 8.8
- **Research project:** Analysed the special education policy in Kerala, particularly with regard to the transition from a special school to a regular school. 

### Sacred Heart College, Mahatma Gandhi University

BA. Economics

Kerala, India

2014 - 2017

- Project: Consumer perceptions about organic food.  

 Conference Publications {data-icon=file}
--------------------------------------------------------------------------------

### Performing Qualitative Data Analysis as a Blind Researcher: Challenges, Workarounds and Design Recommendations
In The 24th International ACM SIGACCESS Conference on Computers and Accessibility(ASSETS ’22). [DOI](https://doi.org/10.1145/3517428.3551356

N/A

2022

O. Aishwarya

### Teachers’ Perceptions around Digital Games for Children in Low-resource Schools for the Blind 

In CHI Conference on Human Factors in Computing Systems (CHI ’21)

N/A

2021

With Gesu India, Vidhya Y, Nirmalendu Diwakar, Mohit Jain, Aditya Vashistha, and Manohar Swaminathan

Poster Presentations {data-icon=file}
--------------------------------------------------------------------------------

### A participatory Design Approach for the Global South: Lessons from Designing a Tool for the Comprehension of Tactile Graphics for Children with Visual Impairments in India 

Empower, 2022 

N/A

2022

With Amit Prakash and Supriya Dey

### Play to Learn and Learn to Play: Designing Card games for Inculcating Numeracy Skills for children with Visual Impairments

Empower, 2019

N/A

2019

With Amit Prakash, Supriya Dey, Manohar Swaminathan, Gesu India, and Jyoti Bhisht.

Presentations {data-icon=file}
--------------------------------------------------------------------------------

###  State of the Art in Assistive Technology for People with Visual Disabilities Empower, 2022 

Invited guest lecture at the Workshop on Assistive Technology for Rehabilitation Professionals, Organized by the Rehabilitation Council of India. 

N/A

2022

O. Aishwarya

### Tactile Art: from Hobby to Research

At the Workshop on Tactile Interactivity, Organized by the Disability Innovation Hub and Center for Accessibility in the Global South at IIITB.

N/A

2022

O. Aishwarya

### Hands-on and Hand-in-hand: Building Virtual Makerspaces that are Accessible to people with Visual Disabilities

At the Workshop on Accessible AR and VR Systems. in CHI2021.

N/A

2021

::: aside

Fellowships and Scholarships {#fellowships}
--------------------------------------------------------------------------------

- #### I Can Lead Fellow (2020-2021)

- One of 12 women with disabilities selected for the fellowship, conducted by Rising Flame.

- #### Course on Designing and Creating Assistive Technology Solutions (2021)  

- Scholarship  by National Institute of Speech and Hearing, Trivandrum

- #### Course on Methods and Statistics in Social Sciences

- Financed  by Coursera


- #### Accessibility Training:  document accessibility Track  

- completed with  scholarship for persons with disabilities by Deque University


This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown).

Last updated on `r Sys.Date()`.

:::
