---
title: "Celebrating touch: A memoir of my journey with Braille"
description: "On World Braille Day, I share my story with Braille, in the hopes that it will enable parents and caregivers to make an informed choice about braille literacy."
author:
  - name: Aishwarya Othena
    url: https://aishwaryaothena.github.io
date: 01-04-2024
categories: [Accessibility, Disability] # self-defined categories
citation: 
  url: https://aishwaryaothena.github.io/disability/2024-01-04-braille/ 
draft: false # setting this to `true` will prevent your post from appearing on your listing page until you're ready!
---

As the world unites to celebrate World Braille Day on January 4th, I cannot help but think back on My journey with braille. World Braille Day, marked on the birthday of Louis Braille, the ingenious creator of this script, serves as a global recognition of the empowerment and inclusivity that Braille represents. Each year, individuals unite on World Braille Day to commemorate this ingenious script and enlighten society about its wonders. Traditionally, I've utilized this occasion to dispel myths surrounding Braille, shedding light on what it truly is and debunking misconceptions. However, for this year's commemoration, I've opted for a different approach. In this essay, I aim to delve into my personal journey with Braille, using it as a lens to explore some of the central debates surrounding Braille in contemporary discourse. After all,  everything personal carries broader societal implications.

	I have been blind since birth, but braille entered my life only in 5th grade. Till then, I tried, with hardly any functional vision at all, to read and write print. I could only read or write in about 100 pt font size, when the letters were written in  thick, dark lines, and that too only under a table lamp kept 15 Cm from the page. Are you wondering why it took some long for me to the introduced to braille? Twenty-eight years ago, nobody in India had heard of a functional vision test. A functional vision test, if I had been given one, would have concluded that I was realistically never going to use print as my primary medium, and, wishful thinking aside, I would need an alternative way to read and write: braille. In the lack of a functional vision test, it was left to the professionals in my life to decide how I should learn. Sighted professionals with hardly any experience of blindness, I should add. Ophthalmologists suggested that teaching me braille would perhaps  make me stop using what little vision I had, leading to even less sight, and my parents agreed. A ludicrous idea, given that I barely had any vision to start with, and what I did have wasn't all that useful in a practical sense. Often, parents of children with disabilities are inundated with facts, may-bes and superstitious nonsense from every quarter, to an extent that making an informed choice is difficult. They often stumble around in the dark (yes, pun intended), trying to figure out what works for them and their child. This prejudice about braille (that it would somehow make me more blind than I already was) had infected me as well. Just like my parents and others around me, I didn’t want to do anything that would make me look more blind.

In the end: the truth was undeniable. I hardly had any vision now, and it was unlikely that I would “get back” the sight I never had, like one of those miraculous characters Indian TV seriels. And every day, it was getting harder and harder for me to function well in the academic world without a way to read and write. Math was becoming a bigger problem than ever, my spelling was atrocious, and the list of things my parents had to read aloud to me was growing longer by the day. 

Eventually, inevitably, my classes began. And almost instantly, I fell in love with braille. I didn’t  have to try so desperately to keep my ever-moving, dancing eyes on a print letter any more. In contrast, braille was almost easy. I marveled at the beauty of this code, designed so perfectly to fit under fingertips. There was a certain kind of beauty in the rhythm of silent fingers, gliding over little white dots. There was a certain magic in the dance of my fingers over Braille, a dance that transforms a series of dots into the poetry of language. In each touch, I found not just letters but a key to a universe waiting to be explored. I could take down notes and read them back to myself. I could read my textbooks. Of course I didn’t attain my fluency and reading speed instantaneously, but this little taste of independence  motivated me to try.

Besides the obvious, I had a hidden hope tucked away in a secret corner of my heart, which became one of my main reasons to persevere, a hope I told no-one about. By this time I was already in love with books. I had finished all 21 of Enid Blyton’s Famous Five novels, and was beginning Harry Potter. If I had my way, I would have beguiled away all my leisure time in reading. Waiting for my father to get back from work (leisure reading was his responsibility, and school work my mother’s) was a lesson in patience. But now, a new possibility entered my mind. What if I could read the rest of the Harry Potter series by myself? In braille? Maybe, if I worked hard enough on mastering the script, this could be possible. I saw no reason it shouldn’t be, unacquainted as I was with the complexities involved. It seemed logical to me. My sighted friends (I only had sighted friends then) cousins, and other family members had all learnt how to read and write, and now they all read independently. They were encouraged to read more and more. I saw no reason why that shouldn’t be the case with me as well.

But (I suppose you could all hear the but coming), of course, it was not that easy. There were several factors I hadn’t factored into my initially simple-sounding equation. Print books are everywhere, while searching for a braille book feels like a badly-designed treasure-hunt. It’s simple, really. My sighted friends and family members acquired new reading material in several ways: they bought books; they borrowed from the library; or they borrowed from their friends and family. None of these avenues were open to me. Book shops did’t stock braille book. I had no braille-reading friends or family members. There were a few libraries, but most of them were far from my home. Only one braille library existed in my city, and because they considered braille books too precious and easily damaged, they didn’t allow readers to take these books home. We were allowed only to read them in the library premises, which made this idea impractical. The only other way to obtain braille books was to have them printed at a braille press at 3-4 rupees per page. Remember that each page of print translates into about 2-3 pages of braille, and then imagine what a large book, say, Harry Potter and the Order of the Phoenix, would cost, and  look like, in braille. Braille books were too expensive for the average Indian family to afford, and too bulky to be stored comfortably. I had to give up on my dream of reading my favorite books in braille.

A print reader, as soon as she masters her letters, has plenty of reading material to practice her reading skills on: Textbooks, other books, hoardings, street signs, shop names, periodicals, and even birthday cards. Everyone around her is also a print reader, can support her when she falters, and correct her when she misreads. Her teachers understand (and check) her notes and answer sheets. Typically, adults in her life also read print fluently. She therefore knows what level of fluency she can aspire to. A braille reader, however, does not typically have these advantages. There is hardly any reading material in braille. The lucky ones have access to textbooks, but that’s about it. No books, or street signs or birthday cards. Some children who study in special schools, know adults who read braille, but for the child in a regular school, no-one around her reads or writes braille. Everyone around her is typically too busy talking about how braille looks so difficult to them to make sure she can read and write competently. Is it any wonder then, that children sometimes end up picking up braille slower?

In a year’s times since I began my braille classes, I took what I retrospectively realize was a big step. I began actively using braille in school. It was the first  time I actively and willingly adopted something that marked me as different from my peers. In hindsight, I was always different, but that was the first time I accepted it. I put my needs and convenience above my worry of what others would think of me, and what labels they would now apply to me. I took the first step towards self-realization.

I hadn’t forgotten my dream of reading independently, though. I took a different approach to it. I learnt how to use a computer with the help of a screen reader. Ebooks, after all, were not hard to come by. I dedicated almost a year to reading the classics (this was in 8th grade, I remember), because I had a folder full of classics on my computer, alphabetized by author names. I was in bliss. The Count of Monte Cristo, Lord of the Rings, Treasure Island, Dracula, Sherlock Holmes… I read… no, I devoured them all. I hadn’t thought about what I preferred: braille or audio. Indeed, I think I subcontiously knew that there was no choice, really, not at that time, given the state of the braille sector in India.

Time passed. In 11th grade, finding that it was a bit difficult to do very spatial things like accounts with a braille slate and stylus, I began using a laptop in school. I slowly stopped using braille. I kept a braille diary for a long time, I remember, but at some point, that too made a digital transition. I used braille occasionally for labeling things, writing down my points and notes for presentations I gave, and so on. My primary medium for reading and writing, however, had now  shifted to typing on a computer.

It is in 2018 that the braille technology sector in India underwent a significant shift, which forever changed how I view braille and my relationship with it. Until then, the only feasible ways of writing braille were either to use a braille slate and a stylus to manually punch the dots onto paper (the braille equivalent of pen and paper) or using a brailler (the braille equivalent to typewriters). I knew, of course, that braille displays existed, but hardly anyone had even seen them in India. Braille displays (sometimes also called notetakers) are a little like computers. They have braille screens with pins moving up and down to form letters. The ones available in the US prior to 2018 were exorbitantly priced, because of the cost involved in moving the pins up and down. To write, these units had a small Perkins braille keyboard rather than QWERTY. It was around 2017-2018 that, almost simultaneously, 2 companies found alternative ways of moving the pins up and down in a way that was much less expensive. These devices brought down the price to such an extent that it became reasonably affordable to people in India and other developing countries.

Finally, the secret hope I had cherished in my heart all those years ago became a reality. I could read anything I wanted, any time I wanted, in braille. I could connect it to my phone or PC and read its screen in braille. The first few days after I received the device, I re-read Harry Potter on it, just for the nostalgia of it.

People ask me which I prefer: braille or a laptop with a screen reader. Rather than choose one over the other, I prefer to think of this as choosing the right tool for the right job. I like to use braille for long-form reading, or reading with my full concentration. When I had enrolled in courses at my institute, I liked to do my course readings in braille as well. It is a great help in my music classes, which is easier because I can read the lyrics, too. For browsing the internet casually, answering my emails and a myriad other things I do daily, I use my screen reader. I see no reason to choose just one way of accessing content. Not when I can use both, and mix and match in any way I want.

“But isn’t braille getting obsolete?” People ask me. “Is there a need for braille when everything can be done on the computer nowadays?” Well, first, braille has also gone digital. I see more possibility now rather than a decline. With the advent of affordable braille displays,  braille has been more accessible and widely available than ever. I read much more now on the device than I used to get a chance to read on paper. Second, the increase of interest by people from the blind community to take up STEM subjects has actually necessitated more rigger in braille instruction. Many blind engineers and mathematicians have spoken about how braille makes it so much easier to navigate through dense programming code and solve complex equations. Third, learning braille makes it easier to understand punctuations as well as text  formatting such as bold, italics and underline.

It is far too soon to call braille obsolete. If the advent of digital devices have merely changed the way people access print rather than making print obsolete, why should we have this conversation for braille at all? If reading audiobooks in the car does not make people come up to you and say “time to put away your pen and paper, and only use audio,” I don’t see why my use of screen readers part of the time should make people come up to me to make these arguments. Furthermore, Had Louis Braille heeded his nay-sayers a few centuries ago, today's blind individuals would not have access to a writing system. We would be limited to reading at a slower pace by tracing embossed print letters with our fingers, perpetually trailing behind others in our reading speed. But he believed that we should all have a way to write, as well.

Braille is, of course, a choice. There will certainly be those who prefer screen readers to it. People who acquired their blindness later in life, for instance, have already grown up using print, and might not need to replace it with another system of reading and writing.  For blind people to be able to make that choice in an informed manner, unstained by prejudice, professionals and caregivers should first be willing to look past their own prejudices to see what braille actually is. The children of today, have choices, unlike those of us who grew up in the pre-braille display era. Let the children of tomorrow have as much access to as many experiences as we can give them, unencumbered with the sighted world’s prejudices on what is necessary or right for them.

